services:
  db:
    image: postgres:15
    container_name: siia_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME:-siia}
      POSTGRES_USER: ${DB_USER:-lopinhos}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-senha123}
    ports:
      - "5432:5432"
    volumes:
      - siia_postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
      - ./model.sql:/docker-entrypoint-initdb.d/02-model.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-lopinhos} -d ${DB_NAME:-siia}"]
      interval: 5s
      timeout: 5s
      retries: 20

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    container_name: siia_web
    restart: unless-stopped
    env_file: .env
    environment:
      - DATABASE_URL=postgresql://${DB_USER:-lopinhos}:${DB_PASSWORD:-senha123}@db:5432/${DB_NAME:-siia}
      - FLASK_DEBUG=${FLASK_DEBUG:-1}
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy

volumes:
  siia_postgres_data:
    driver: local
